Bump rhysd/actionlint from 1.7.5 to 1.7.6

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -23,21 +23,25 @@ jobs:
   get-versions:
     name: Get 3 latest versions
     runs-on: ubuntu-latest
-    timeout-minutes: 3
+    timeout-minutes: 10
     outputs:
       versions: ${{ steps.prepare-list.outputs.versions }}
     steps:
+      - name: Get releases
+        id: github-releases
+        uses: yakubique/github-releases@v1.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          repository: "jolie/jolie"
+          sort: "desc"
       - name: Prepare list
         id: prepare-list
         env:
           RELEASES_AMOUNT: "3"
-          TARGET_REPO: "jolie/jolie"
         run: |
-          versions=$(curl -sL \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${TARGET_REPO}/releases" \
-            | jq -c -r --arg n "${RELEASES_AMOUNT}" '[.[0:($n | tonumber)][].tag_name] | map(sub("^v"; "")) | . += ["latest"]')
+          versions=$(echo '${{ steps.github-releases.outputs.releases }}' \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '.[0:($n | tonumber)] | map(sub("^v"; "")) | . += ["latest"]')
           echo "versions=${versions}" >> "$GITHUB_OUTPUT"
   setup-jolie:
     name: Setup jolie
@@ -65,7 +69,7 @@ jobs:
               exit 1
             fi
           }
-          test_equal "jolie should not be installed" \
+          test_equal "jolie should be installed" \
             "${{ steps.setup-jolie.outputs.installed }}" \
             "true"
       - name: Print version
@@ -86,6 +90,17 @@ jobs:
       - name: Setup Jolie
         id: setup-jolie
         uses: ./
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "jolie should be installed" \
+            "${{ steps.setup-jolie.outputs.installed }}" \
+            "true"
       - name: Print version
         run: jolie --version
   test-force:
@@ -102,10 +117,13 @@ jobs:
       - name: Setup Jolie 1
         id: setup-jolie-1
         uses: ./
+        with:
+          version: "1.12.2"
       - name: Setup Jolie 2
         id: setup-jolie-2
         uses: ./
         with:
+          version: "1.12.2"
           force: ${{ matrix.force }}
       - name: Test action completion
         run: |
