perf: install jolie via java -jar command (#27)
<!-- markdownlint-disable-file MD041 -->

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] I have read the
[CONTRIBUTING](https://github.com/fabasoad/setup-jolie-action/blob/main/CONTRIBUTING.md)
      doc.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been reviewed and added / updated if needed (for bug
fixes / features).

## Pull request type

<!-- Please do not submit updates to dependencies unless it fixes an
issue. -->

<!-- Please try to limit your pull request to one type, submit multiple
pull
requests if needed. -->

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior

<!-- Please describe the current behavior that you are modifying, or
link to a
relevant issue. -->

## What is the new behavior

<!-- Please describe the behavior or changes that are being added by
this PR. -->

-
-
-

## Does this introduce a breaking change

- [ ] Yes
- [ ] No

<!-- If this introduces a breaking change, please describe the impact
and
migration path for existing applications below. -->

## Other information

<!-- Any other information that is important to this PR such as
screenshots of
how the component looks before and after the change. -->
<!-- This document was adapted from the open-source
[appium/appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
repository. -->

---

Closes #{IssueNumber}

---------

Co-authored-by: Eugene Fabizhevskyi <yevhen.fabizhevskyi@woven.toyota>

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -20,8 +20,8 @@ defaults:
     shell: sh
 
 jobs:
-  get-versions:
-    name: Get 3 latest versions
+  get-jolie-versions:
+    name: Get 3 latest jolie versions
     runs-on: ubuntu-latest
     timeout-minutes: 10
     outputs:
@@ -45,22 +45,23 @@ jobs:
           echo "versions=${versions}" >> "$GITHUB_OUTPUT"
   setup-jolie:
     name: Setup jolie
-    needs: [get-versions]
+    needs: [get-jolie-versions]
     runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 10
     strategy:
       fail-fast: false
       matrix:
         os: ["ubuntu", "windows", "macos"]
-        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
+        jolie-version: ${{ fromJSON(needs.get-jolie-versions.outputs.versions) }}
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
-      - name: Setup Jolie
+      - name: Setup jolie
         id: setup-jolie
         uses: ./
         with:
-          version: ${{ matrix.version }}
+          jolie-version: ${{ matrix.jolie-version }}
+          jpm-installation-mode: "skip"
       - name: Test action completion
         run: |
           test_equal() {
@@ -70,12 +71,70 @@ jobs:
             fi
           }
           test_equal "jolie should be installed" \
-            "${{ steps.setup-jolie.outputs.installed }}" \
+            "${{ steps.setup-jolie.outputs.jolie-installed }}" \
             "true"
+          test_equal "jpm should not be installed" \
+            "${{ steps.setup-jolie.outputs.jpm-installed }}" \
+            "false"
       - name: Print version
         run: jolie --version
-  setup-jolie-in-container:
-    name: Setup jolie in container (${{ matrix.image }}, latest)
+  get-jpm-versions:
+    name: Get 3 latest jpm versions
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    outputs:
+      versions: ${{ steps.prepare-list.outputs.versions }}
+    steps:
+      - name: Prepare list
+        id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
+          TARGET_REPO: "jolie/jpm"
+        run: |
+          versions=$(curl -sL \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${TARGET_REPO}/tags" \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '[.[0:($n | tonumber)][].name] | map(sub("^v"; "")) | . += ["latest"]')
+          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
+  setup-jpm:
+    name: Setup jpm
+    needs: [get-jpm-versions]
+    runs-on: ${{ matrix.os }}-latest
+    timeout-minutes: 10
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ["ubuntu", "windows", "macos"]
+        jpm-version: ${{ fromJSON(needs.get-jpm-versions.outputs.versions) }}
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup jolie
+        id: setup-jolie
+        uses: ./
+        with:
+          jpm-version: ${{ matrix.jpm-version }}
+          jolie-installation-mode: "skip"
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "jpm should be installed" \
+            "${{ steps.setup-jolie.outputs.jpm-installed }}" \
+            "true"
+          test_equal "jolie should not be installed" \
+            "${{ steps.setup-jolie.outputs.jolie-installed }}" \
+            "false"
+      - name: Print version
+        run: jpm --version
+  setup-jolie-jpm-in-container:
+    name: Setup jolie & jpm in container (${{ matrix.image }}, latest)
     runs-on: ubuntu-latest
     timeout-minutes: 5
     container:
@@ -87,7 +146,7 @@ jobs:
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
-      - name: Setup Jolie
+      - name: Setup jolie
         id: setup-jolie
         uses: ./
       - name: Test action completion
@@ -99,32 +158,38 @@ jobs:
             fi
           }
           test_equal "jolie should be installed" \
-            "${{ steps.setup-jolie.outputs.installed }}" \
+            "${{ steps.setup-jolie.outputs.jolie-installed }}" \
+            "true"
+          test_equal "jpm should be installed" \
+            "${{ steps.setup-jolie.outputs.jpm-installed }}" \
             "true"
       - name: Print version
-        run: jolie --version
-  test-force:
-    name: Test force
+        run: |
+          jolie --version
+          jpm --version
+  test-jolie-jpm-installation-mode:
+    name: Test jolie & jpm installation mode
     runs-on: ubuntu-latest
     timeout-minutes: 10
     strategy:
       fail-fast: false
       matrix:
-        force: ["true", "false"]
+        installation-mode: ["skip", "idempotent", "always"]
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
-      - name: Setup Jolie 1
+      - name: Setup jolie 1
         id: setup-jolie-1
         uses: ./
         with:
-          version: "1.13.1"
-      - name: Setup Jolie 2
+          jolie-installation-mode: "${{ matrix.installation-mode }}"
+          jpm-installation-mode: "${{ matrix.installation-mode }}"
+      - name: Setup jolie 2
         id: setup-jolie-2
         uses: ./
         with:
-          version: "1.13.1"
-          force: ${{ matrix.force }}
+          jolie-installation-mode: "${{ matrix.installation-mode }}"
+          jpm-installation-mode: "${{ matrix.installation-mode }}"
       - name: Test action completion
         run: |
           test_equal() {
@@ -133,9 +198,15 @@ jobs:
               exit 1
             fi
           }
-          test_equal "Wrong \"installed\" output from setup-jolie-1" \
-            "${{ steps.setup-jolie-1.outputs.installed }}" \
-            "true"
-          test_equal "Wrong \"installed\" output from setup-jolie-2" \
-            "${{ steps.setup-jolie-2.outputs.installed }}" \
-            "${{ matrix.force }}"
+          test_equal "Wrong \"jolie-installed\" output from setup-jolie-1" \
+            "${{ steps.setup-jolie-1.outputs.jolie-installed }}" \
+            "${{ matrix.installation-mode != 'skip' }}"
+          test_equal "Wrong \"jolie-installed\" output from setup-jolie-2" \
+            "${{ steps.setup-jolie-2.outputs.jolie-installed }}" \
+            "${{ matrix.installation-mode == 'always' }}"
+          test_equal "Wrong \"jpm-installed\" output from setup-jolie-1" \
+            "${{ steps.setup-jolie-1.outputs.jpm-installed }}" \
+            "${{ matrix.installation-mode != 'skip' }}"
+          test_equal "Wrong \"jpm-installed\" output from setup-jolie-2" \
+            "${{ steps.setup-jolie-2.outputs.jpm-installed }}" \
+            "${{ matrix.installation-mode == 'always' }}"
